# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/SignallingWebServer/" # Location of package manifests
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/SFU/" # Location of package manifests
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Matchmaker/" # Location of package manifests
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Frontend/implementations/typescript" # Location of package manifests
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Frontend/library/" # Location of package manifests
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"  
